### ISSUE TITLE
AWS 실습 세미나

### ISSUE THREAD

**Issue by tea7day** [wooritech/story-g#26]
### 개요

- **목적:** AWS 기술 공유
- **진행방법:** 1~2주마다 1회씩 AWS 주요 서비스에 대한 실습 진행 및 토의

### AWS 실습 세미나 - 1차 

- **주제: AWS 실습 세미나 개요 설명**
- 일시: 2018/01/08 13:00~13:40 (40분)
- 참여자: 서승현, 김충식, 강구창, 김상엽
- [발표 자료](https://docs.google.com/presentation/d/1gHbsAhgdJX0-PINJjk0nVnPpZ6uo1Lm8HbuXX3Sh_es/edit?usp=sharing)

**Comment by KIMSANGYEOB** [comment]
## 클라우드&AWS의 흐름
클라우드 부터 AWS 까지 핵심적인 개요 및 흐름을 알 수 있는 좋은 시간이였습니다.

클라우드는 왜 필요한가 부터 시작해서 클라우드 성장 과정의 흐름을 파악하고 **AWS**가 어떤 **역할**을 하고 어떤것으로 **구성** 되어있는지 과정을 통해 쉽게 이해할 수 있었네요.

전 클라우드가 거의 저장용도라고만 생각하고 있었는데 승현씨 세미나를 들으니 **개발 플랫폼**으로써 많은 기업들이 사용하고 있으며 관심을 많이 가져야 겠다는 생각이 와 닿았습니다.

다음에 실습 진행 및 토의가 기대됩니다.
좋은시간 내주셔서 감사합니다.  👍

**Comment by tea7day** [comment]
### AWS 실습 세미나 - 2차 

- 내용: AWS 클라우드에서 서버 구성하기
  - IAM 계정 생성
  - Cloud9 개발환경 구성
  - EC2 서버 만들기
  - 샘플 어플리케이션 배포하기
- 일시: 2018/01/22 18:30~20:10 (1시간 40분)
- [진행 자료](https://github.com/tea7day/aws-seminar)

**Comment by tea7day** [comment]
### AWS 실습 세미나 - 3차 

- 내용: 서버 제대로 쉽게 구성하기
  - 서버를 제대로 구성하는 방법
    - 인터넷 검색이 아닌 공식 홈페이지 문서를 보고 설치하자!
    - 나만의 설치 문서를 작성하고 저장하자!
  - 서버를 쉽게 구성하는 방법
    - docker를 활용한 서버 구성 & 깃으로 소스관리
    - mysql / nginx / wordpress
  - 자바스크립트에서 mysql 사용하기
    - react <-> nodejs(sequelize) <-> mysql(docker)
- 일시: 2018/01/30 18:50~20:20 (1시간 30분)
- 참여자: 서승현, 김충식,  김상엽
- [진행 자료](https://github.com/tea7day/aws-seminar)

**Comment by tea7day** [comment]
### AWS 실습 세미나 - 4차 

- **주제: 서버리스**
  - 서버리스 스타일로 웹어플리케이션 구성하기
     - Lab 1: S3 정적 웹사이트 구성
     - Lab 2: Cognito를 활용한 인증 서비스 구성
     - Lab 3: DynamoDB 테이블 구성까지 진행 완료
- 일시: 2018/02/06 18:40~20:00 (1시간 20분)
- 참여자: 서승현, 김충식,  김상엽
- [진행 자료](https://github.com/awskrug/aws-serverless-workshops/tree/master/WebApplication)

**Comment by onlydel** [comment]
[AWS 2018 summit seoul](https://aws.amazon.com/ko/summits/seoul/?sc_channel=em&sc_campaign=APAC_EV_kr-summit-seoul_20180418&sc_publisher=aws&sc_medium=em_73725&sc_content=event_gc_summit&sc_country=kr&sc_geo=apac&sc_category=mult&sc_outcome=event&trkCampaign=summit-seoul-18&trk=em_inv1_2017event&mkt_tok=eyJpIjoiTldVeE5XUTVZelJrTUdGaSIsInQiOiJWanNPUFIyc1p3MTBsSGFaK1ltRXFSemZ3bWhVVUV4aXdKdHg4eTh0UGZPRHBYam5Xa1lNZThFVUZmZExPTGp2WmlKYUMxSStJZUNPWDNDMlJ4SWR5MGtcLzZSelNXZXhlTVQzXC9NdWk4cUtTUW00YnFpcXNsNXRwQ1dVVHNKTlZRIn0%3D) 이 4월에 있습니다. 세미나팀 참석해서 관전하면 좋을 것 같습니다.

**Comment by tea7day** [comment]
### AWS 실습 세미나 - 5차 

- **주제: 서버리스**
  - 서버리스 스타일로 웹어플리케이션 구성하기
     - Lab 3: Lambda 구성
     - Lab 4: API Gateway 구성 및 테스트
  - 서버리스 소개 동영상 시청
  - 서버리스를 활용한 이미지 인식 챗봇(순시리) 소개
- 일시: 2018/02/20 19:00~20:30 (1시간 30분)
- 참여자: 서승현, 강구창
- 진행 자료
  - [서버리스 웹앱 튜토리얼](https://github.com/awskrug/aws-serverless-workshops/tree/master/WebApplication)
  - [람다 소개 동영상 (~12:00분)](https://www.youtube.com/watch?v=7aN5uWLCci8&t=900s)
  - [서버리스 챗봇](https://github.com/tea7day/aws-seminar/tree/master/05-serverless/slack-image-bot)

**Comment by tea7day** [comment]
AWS 세미나는 시즌1은 종료되었습니다.
