### ISSUE TITLE
과자 쿠폰 발급

### ISSUE THREAD

**Issue by tea7day** [wooritech/story-g#27]
매주 또는 매일 베이스 사이트에서 과자 쿠폰을 발급(종이 형태로 출력) 받고 
해당 쿠폰 1개당 과자1개를 교환해서 먹을 수 있게 하기

단, 쿠폰이 없을 경우, 돈(100원)으로 구입 가능

쿠폰은 개수가 정해져 있을 수도 있지만, 또는 어떤 일에 대한 보상으로 주어질 수도 있음.

**Comment by onlydel** [comment]
### #19 우리코인과 연동
우리테크에서 발급한 복지코인인 우리코인과 연동 가능
